#file: noinspection HttpUrlsUsage

logging:
  level:
    com.seyed.ali.ApiGateway.service.UserProxyService: TRACE

--- # keycloak
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${DC_KEYCLOAK_SERVER_HOST:localhost}:8080/realms/DevVault-v2.0

--- # Eureka client
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${DC_EUREKA_SERVER_HOST:localhost}:8761/eureka
#      defaultZone: http://discovery-server:8761/eureka

--- # API Gateway
spring:
  cloud:
    gateway:
      routes:
        - id: Time-Entry-Service
          uri: lb://Time-Entry-Service
          predicates:
            - Path=/api/v1/time/**

        - id: Authentication-Service
          uri: lb://Authentication-Service
          predicates:
            - Path=/keycloak-user/**
        - id: Authentication-Service
          uri: lb://Authentication-Service
          predicates:
            - Path=/hello
        - id: Authentication-Service
          uri: lb://Authentication-Service
          predicates:
            - Path=/keycloak/**

--- # Custom Variables
microservice:
  authentication-service:
    url: ${MICROSERVICE_AUTHENTICATION_SERVICE_URL:http://Authentication-Service/keycloak-user}
    endpoint-url: ${MICROSERVICE_AUTHENTICATION_SERVICE_ENDPOINT_URL:/handle-user}
